# Generated by Django 5.1.2 on 2024-11-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('products', models.ManyToManyField(null=True, to='pages.video')),
            ],
        ),
    ]
