# Generated by Django 5.1.2 on 2024-11-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_video_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='products',
            new_name='watch',
        ),
    ]
