# Generated by Django 5.1.2 on 2024-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
